# config.yml for manual version

# List of plugins to exclude from updates
excludedPlugins:
  - MyPlugin

# Update URLs for plugins
pluginUpdateUrls:
  MyOtherPlugin: https://example.com/plugins/MyOtherPlugin.jar
  AnotherPlugin: https://example.com/plugins/AnotherPlugin.jar
